Repository riscv-boom/riscv-boom, pull requests merged in 2019-05, with the labels that each got.

#258 Fixed doc copyright to be UCB
  docs/conf.py
Labels: bug, docs

#259 Update LICENSE
  LICENSE
Labels: cleanup

#269 add hart to boom printfs
  src/main/scala/bpu/bpd/gshare/gshare.scala
  src/main/scala/bpu/bpd/simple-predictors/base-only.scala
  src/main/scala/bpu/bpd/simple-predictors/simple-predictors.scala
  src/main/scala/bpu/bpd/tage/tage-table.scala
  src/main/scala/bpu/bpd/tage/tage.scala
  src/main/scala/bpu/btb/bim.scala
  src/main/scala/bpu/btb/btb-sa.scala
  src/main/scala/bpu/btb/dense-btb.scala
  src/main/scala/exu/core.scala
  src/main/scala/exu/execution-units/execution-unit.scala
  src/main/scala/exu/execution-units/execution-units.scala
  src/main/scala/exu/fp-pipeline.scala
  src/main/scala/exu/register-read/regfile.scala
  src/main/scala/exu/rob.scala
  src/main/scala/ifu/icache.scala
Labels: cleanup, enhancement

#270 fix to allow more than 2 boom cores in configs
  src/main/scala/common/configs.scala
Labels: bug, enhancement

#272 add support for boom being first hart
  src/main/scala/system/ConfigMixins.scala
Labels: enhancement

#274 Small clarifications to HPMs
  docs/sections/uarch-counters.rst
Labels: cleanup, docs

#268 Fake chicken-bit CSR
  src/main/scala/common/parameters.scala
Labels: cleanup, enhancement
