Repository riscv-boom/riscv-boom, pull requests merged in 2019-09, with the labels that each got.

#381 update to newest chipyard for parallel builds
  .circleci/defaults.sh
  .circleci/do-rtl-build.sh
  .circleci/prepare-for-rtl-build.sh
  .circleci/run-tests.sh
  CHIPYARD.hash
Labels: ci

#366 DCache prefetching + multi-issue
  .circleci/config.yml
  .circleci/do-rtl-build.sh
  src/main/scala/common/config-mixins.scala
  src/main/scala/common/parameters.scala
  src/main/scala/exu/core.scala
  src/main/scala/exu/execution-units/execution-units.scala
  src/main/scala/exu/fp-pipeline.scala
  src/main/scala/exu/issue-units/issue-slot.scala
  src/main/scala/exu/issue-units/issue-unit-prioritizing.scala
  src/main/scala/exu/rob.scala
  src/main/scala/lsu.diff
  src/main/scala/lsu/dcache.scala
  src/main/scala/lsu/lsu.scala
  src/main/scala/lsu/mshrs.scala
  src/main/scala/lsu/prefetcher.scala
  src/main/scala/lsu/tlb.scala
  src/main/scala/patch
  util/csmith/run-csmith.sh
Labels: enhancement

#384 [tile] Flatten BOOM Tile organization
  src/main/scala/common/rocc.scala
  src/main/scala/common/tile.scala
  src/main/scala/exu/core.scala
  src/main/scala/ifu/frontend.scala
  src/main/scala/lsu/types.scala
Labels: cleanup

#394 [core] Remove unsupported parameters
  src/main/scala/common/parameters.scala
  src/main/scala/exu/core.scala
  src/main/scala/exu/execution-units/functional-unit.scala
  src/main/scala/exu/register-read/regfile-custom.scala
  src/main/scala/exu/rename/rename-stage.scala
  src/main/scala/lsu/lsu.scala
Labels: cleanup

#393 [core] Refactor CfiTypes constants
  src/main/scala/bpu/btb/btb-sa.scala
  src/main/scala/bpu/btb/btb.scala
  src/main/scala/bpu/btb/dense-btb.scala
  src/main/scala/common/consts.scala
  src/main/scala/common/micro-op.scala
  src/main/scala/exu/decode.scala
  src/main/scala/exu/execution-units/functional-unit.scala
  src/main/scala/ifu/branch-checker.scala
  src/main/scala/ifu/fetch-control-unit.scala
  src/main/scala/ifu/fetch-monitor.scala
  src/main/scala/ifu/fetch-target-queue.scala
Labels: cleanup

#387 Disallow UnifiedMemInt issue queues
  .circleci/config.yml
  .circleci/defaults.sh
  .circleci/run-tests.sh
  CHIPYARD.hash
  src/main/scala/common/config-mixins.scala
  src/main/scala/common/parameters.scala
  src/main/scala/exu/core.scala
  src/main/scala/exu/decode.scala
  src/main/scala/exu/execution-units/execution-unit.scala
  src/main/scala/exu/execution-units/execution-units.scala
  src/main/scala/exu/issue-units/issue-units.scala
Labels: cleanup

#392 [core] Remove redundant MicroOpWithData bundle
  src/main/scala/common/micro-op.scala
  src/main/scala/exu/execution-units/execution-unit.scala
  src/main/scala/exu/fp-pipeline.scala
  src/main/scala/lsu/lsu.scala
Labels: cleanup
