Repository riscv-boom/riscv-boom, pull requests merged in 2019-07, with the labels that each got.

#319 Early Out Divider
  src/main/scala/common/parameters.scala
Labels: performance bug

#326 cleanup configs
  src/main/scala/system/Configs.scala
Labels: cleanup

#328 Decode QoR
  src/main/scala/common/micro-op.scala
  src/main/scala/exu/decode.scala
  src/main/scala/ifu/fetch-buffer.scala
  src/main/scala/ifu/fetch-control-unit.scala
  src/main/scala/ifu/old-fetch-buffer.scala
Labels: enhancement

#332 Long Latency Writeback Port Fix
  src/main/scala/exu/core.scala
  src/main/scala/exu/fp-pipeline.scala
  src/main/scala/exu/register-read/regfile.scala
Labels: bug

#322 Remote CI Builds
  .circleci/README.md
  .circleci/build-riscv-tools.sh
  .circleci/build-run-csmith-tests.sh
  .circleci/clean-old-files.sh
  .circleci/config.yml
  .circleci/defaults.sh
  .circleci/do-rtl-build.sh
  .circleci/images/Dockerfile
  .circleci/prepare-for-rtl-build.sh
  .circleci/run-tests.sh
  CHIPYARD.hash
Labels: ci, enhancement

#329 Branch Resolution QoR
  src/main/scala/exu/execution-units/functional-unit.scala
Labels: enhancement

#317 Delayed Dispatch
  src/main/scala/exu/core.scala
  src/main/scala/exu/execution-units/rocc.scala
  src/main/scala/exu/rename/rename-freelist.scala
  src/main/scala/exu/rename/rename-maptable.scala
  src/main/scala/exu/rename/rename-stage.scala
  src/main/scala/lsu/lsu.scala
Labels: cleanup, enhancement

#335 RVC Expansion QoR Tweak
  src/main/scala/ifu/fetch-control-unit.scala
Labels: enhancement

#334 Delay Uncacheable Loads
  src/main/scala/exu/rob.scala
Labels: enhancement

#344 [core/rob] Get exception PC's from FTQ
  src/main/scala/common/micro-op.scala
  src/main/scala/exu/core.scala
  src/main/scala/exu/issue-units/issue-unit.scala
  src/main/scala/exu/rob.scala
  src/main/scala/ifu/fetch-buffer.scala
  src/main/scala/ifu/fetch-monitor.scala
  src/main/scala/ifu/old-fetch-buffer.scala
Labels: enhancement

#342 [rocc] Remove debug_inst
  src/main/scala/exu/execution-units/rocc.scala
Labels: QoR, tapeout

#341 [fcu/ras] RAS Update Regression
  src/main/scala/ifu/fetch-control-unit.scala
Labels: QoR, tapeout

#340 [util] N-wide priority selector QoR
  src/main/scala/util/util.scala
Labels: QoR, tapeout

#343 [ren] Maptable Bypass QoR
  src/main/scala/exu/rename/rename-maptable.scala
Labels: QoR, tapeout

#358 [ifu] Deprecate the old FetchBuffer.
  src/main/scala/common/parameters.scala
  src/main/scala/exu/core.scala
  src/main/scala/ifu/fetch-control-unit.scala
  src/main/scala/ifu/old-fetch-buffer.scala
Labels: cleanup

#359 [ifu] Deprecate support for 3-cycle fetch pipeline
  src/main/scala/common/parameters.scala
  src/main/scala/ifu/fetch-control-unit.scala
Labels: cleanup

#357 [ifu] fetch-controller cleanup
  src/main/scala/ifu/fetch-control-unit.scala
Labels: cleanup

#347 [ren] Separate INT/FP Rename Instantiations
  src/main/scala/exu/core.scala
  src/main/scala/exu/rename/rename-busytable.scala
  src/main/scala/exu/rename/rename-stage.scala
Labels: cleanup
