Repository riscv-boom/riscv-boom, pull requests merged in 2019-06, with the labels that each got.

#277 BOOM Crossings
  src/main/scala/common/configs.scala
  src/main/scala/common/tile.scala
  src/main/scala/lsu/types.scala
  src/main/scala/system/BoomAndRocketSubsystem.scala
  src/main/scala/system/BoomSubsystem.scala
  src/main/scala/system/ConfigMixins.scala
Labels: cleanup, enhancement

#278 Fix Interrupt/Hart Mapping and BOOM Hart 0 Default
  src/main/scala/system/BoomAndRocketSubsystem.scala
  src/main/scala/system/BoomSubsystem.scala
  src/main/scala/system/ConfigMixins.scala
Labels: bug, enhancement

#282 speed up ci by adding fast (removes verbose print)
  .circleci/config.yml
Labels: ci, enhancement

#290 [csmith] Fix csmith run script to allow for arbitrary argument order
  util/csmith/run-csmith.sh
Labels: enhancement

#295 Full ROB Fix
  src/main/scala/exu/rob.scala
Labels: bug

#293 split up generator into functions
  src/main/scala/system/Generator.scala
Labels: cleanup, enhancement

#294 add issue and pull request templates based on rc/chisel/firrtl
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs, enhancement

#289 ROB Head & Tail Fix
  src/main/scala/exu/rob.scala
Labels: bug

#298 Fixed ROB fullness tracking w.r.t. mispredicts
  src/main/scala/exu/rob.scala
Labels: bug

#299 Core cleanup
  src/main/scala/exu/core.scala
Labels: cleanup

#255 Issue Refactor
  src/main/scala/exu/issue-units/issue-slot.scala
  src/main/scala/exu/issue-units/issue-unit-age-ordered.scala
  src/main/scala/exu/rename/rename-busytable.scala
Labels: cleanup, enhancement

#302 alwaysBypassable fix
  src/main/scala/exu/execution-units/execution-unit.scala
Labels: bug

#281 Common refactor
  .circleci/config.yml
  docs/sections/boom-ecosystem.rst
  docs/sections/verification.rst
  src/main/scala/common/configs.scala
  src/main/scala/common/consts.scala
  src/main/scala/common/micro-op.scala
  src/main/scala/common/package.scala
  src/main/scala/common/parameters.scala
  src/main/scala/common/rocc.scala
  src/main/scala/common/tile.scala
  src/main/scala/common/types.scala
  src/main/scala/exu/core.scala
  src/main/scala/exu/decode.scala
  src/main/scala/exu/execution-units/execution-units.scala
  src/main/scala/exu/execution-units/functional-unit.scala
  src/main/scala/exu/execution-units/rocc.scala
  src/main/scala/exu/fp-pipeline.scala
  src/main/scala/exu/issue-units/issue-slot.scala
  src/main/scala/exu/issue-units/issue-unit-age-ordered.scala
  src/main/scala/exu/issue-units/issue-unit-unordered.scala
  src/main/scala/exu/issue-units/issue-unit.scala
  src/main/scala/exu/register-read/func-unit-decode.scala
  src/main/scala/exu/register-read/regfile.scala
  src/main/scala/exu/register-read/register-read.scala
  src/main/scala/exu/rename/rename-busytable.scala
  src/main/scala/exu/rename/rename-freelist.scala
  src/main/scala/exu/rename/rename-maptable.scala
  src/main/scala/exu/rename/rename-stage.scala
  src/main/scala/exu/rob.scala
  src/main/scala/lsu/dcache-shim.scala
  src/main/scala/lsu/lsu.scala
  src/main/scala/system/Configs.scala
  src/main/scala/util/util.scala
Labels: cleanup

#304 Rename Refactor
  src/main/scala/common/parameters.scala
  src/main/scala/exu/core.scala
  src/main/scala/exu/issue-units/issue-unit.scala
  src/main/scala/exu/rename/rename-busytable.scala
  src/main/scala/exu/rename/rename-freelist.scala
  src/main/scala/exu/rename/rename-maptable.scala
  src/main/scala/exu/rename/rename-stage.scala
  src/main/scala/exu/rob.scala
  src/main/scala/util/util.scala
Labels: cleanup, enhancement
