Repository riscv-boom/riscv-boom, pull requests merged in 2019-01, with the labels that each got.

#149 Cache both riscv-tools and verilator for faster CI tests
  .circleci/config.yml
  .circleci/images/Dockerfile
  .circleci/images/README.md
  ci/create-hash.sh
  ci/prepare-for-build.sh
  ci/prepare-riscv-tools.sh
  ci/prepare-verilator-build.sh
Labels: enhancement

#155 [CI] Remove duplicate tests
  .circleci/config.yml
Labels: enhancement

#141 RVC Support
  .circleci/config.yml
  README.md
  ci/README.md
  ci/build-riscv-tools.sh
  docs/sections/FutureWork/futurework.rst
  docs/sections/InstructionFetch/FetchStage.rst
  docs/sections/IntroductionOverview/RISCV-ISA.rst
  src/main/scala/bpu/btb-sa.scala
  src/main/scala/bpu/btb.scala
  src/main/scala/bpu/dense-btb.scala
  src/main/scala/common/configs.scala
  src/main/scala/common/consts.scala
  src/main/scala/common/microop.scala
  src/main/scala/common/parameters.scala
  src/main/scala/exu/core.scala
  src/main/scala/exu/decode.scala
  src/main/scala/exu/fudecode.scala
  src/main/scala/exu/functional_unit.scala
  src/main/scala/exu/rob.scala
  src/main/scala/ifu/branchchecker.scala
  src/main/scala/ifu/fetch.scala
  src/main/scala/ifu/fetchbuffer.scala
  src/main/scala/ifu/fetchmonitor.scala
  src/main/scala/ifu/fetchtargetqueue.scala
  src/main/scala/ifu/frontend.scala
  src/main/scala/lsu/lsu.scala
  src/main/scala/system/BoomTestSuites.scala
  src/main/scala/system/Configs.scala
  src/main/scala/system/Generator.scala
Labels: enhancement, missing feature

#159 csmith random testing
  .circleci/README.md
  .circleci/build-riscv-tools.sh
  .circleci/build-run-csmith-tests.sh
  .circleci/config.yml
  .circleci/create-hash.sh
  .circleci/do-rtl-build.sh
  .circleci/prepare-for-rtl-build.sh
  docs/sections/Verification/verification.rst
Labels: ci, enhancement

#168 Docs Organization
  docs/index.rst
  docs/sections/bibliography/bibliography.bib
  docs/sections/bibliography/bibliography.rst
  docs/sections/branch-prediction/backing-predictor.rst
  docs/sections/branch-prediction/configurations.rst
  docs/sections/branch-prediction/index.rst
  docs/sections/branch-prediction/rocket-nl-predictor.rst
  docs/sections/debugging.rst
  docs/sections/decode-stage.rst
  docs/sections/execution-stages.rst
  docs/sections/faq.rst
  docs/sections/future-work.rst
  docs/sections/instruction-fetch-stage.rst
  docs/sections/intro-overview/boom-pipeline.rst
  docs/sections/intro-overview/boom-repository.rst
  docs/sections/intro-overview/chisel-hcl.rst
  docs/sections/intro-overview/index.rst
  docs/sections/intro-overview/quick-start.rst
  docs/sections/intro-overview/riscv-isa.rst
  docs/sections/intro-overview/rocket-chip.rst
  docs/sections/issue-units.rst
  docs/sections/load-store-unit.rst
  docs/sections/memory-system.rst
  docs/sections/parameterization.rst
  docs/sections/physical-realization.rst
  docs/sections/reg-file-bypass-network.rst
  docs/sections/rename-stage.rst
  docs/sections/reorder-buffer.rst
  docs/sections/terminology.rst
  docs/sections/uarch-counters.rst
  docs/sections/verification.rst
Labels: docs

#171 [exu] Deprecate unpipelined integer multiplier
  .circleci/config.yml
  src/main/scala/exu/execute.scala
  src/main/scala/exu/execution_units.scala
  src/main/scala/exu/functional_unit.scala
Labels: cleanup

#175 [CI] Re-enable BoomConfig and change csmith cmd
  .circleci/build-run-csmith-tests.sh
  .circleci/config.yml
Labels: ci
