Repository riscv-boom/riscv-boom, pull requests merged in 2019-10, with the labels that each got.

#400 [docs] MICRO 2019 Documentation Cleanup
  docs/figures/boom-pipeline-detailed.png
  docs/index.rst
  docs/sections/bibliography/bibliography.rst
  docs/sections/boom-ecosystem.rst
  docs/sections/branch-prediction/backing-predictor.rst
  docs/sections/branch-prediction/index.rst
  docs/sections/branch-prediction/nl-predictor.rst
  docs/sections/debugging.rst
  docs/sections/decode-stage.rst
  docs/sections/execution-stages.rst
  docs/sections/future-work.rst
  docs/sections/instruction-fetch-stage.rst
  docs/sections/intro-overview/boom-pipeline.rst
  docs/sections/intro-overview/boom-repository.rst
  docs/sections/intro-overview/boom.rst
  docs/sections/intro-overview/chisel.rst
  docs/sections/intro-overview/index.rst
  docs/sections/intro-overview/quick-start.rst
  docs/sections/intro-overview/riscv-isa.rst
  docs/sections/intro-overview/rocket-chip.rst
  docs/sections/issue-units.rst
  docs/sections/load-store-unit.rst
  docs/sections/memory-system.rst
  docs/sections/parameterization.rst
  docs/sections/physical-realization.rst
  docs/sections/reg-file-bypass-network.rst
  docs/sections/rename-stage.rst
  docs/sections/reorder-buffer.rst
  docs/sections/terminology.rst
  docs/sections/verification.rst
  src/main/scala/common/config-mixins.scala
  src/main/scala/common/parameters.scala
Labels: cleanup, docs

#404 [ci] Add QEMU dependencies to Docker image
  .circleci/config.yml
  .circleci/images/Dockerfile
Labels: ci

#338 CI Hwacha Support
  .circleci/build-toolchains.sh
  .circleci/config.yml
  .circleci/create-hash.sh
  .circleci/defaults.sh
  .circleci/do-rtl-build.sh
  .circleci/run-tests.sh
  CHIPYARD.hash
  src/main/scala/common/tile.scala
  src/main/scala/ifu/icache.scala
Labels: ci

#397 [iss] Split the issue unit generation
  src/main/scala/common/parameters.scala
  src/main/scala/exu/core.scala
  src/main/scala/exu/issue-units/issue-units.scala
Labels: cleanup

#405 [mshrs] Fix tag update hazard for refills
  src/main/scala/lsu/mshrs.scala
Labels: bug
