Repository riscv-boom/riscv-boom, pull requests merged in 2019-04, with the labels that each got.

#172 Rocket jan2019
  .circleci/create-hash.sh
  .circleci/do-rtl-build.sh
  ROCKETCHIP_VERSION
  src/main/scala/common/parameters.scala
  src/main/scala/common/tile.scala
  src/main/scala/exu/core.scala
  src/main/scala/lsu/types.scala
  src/main/scala/system/BoomSubsystem.scala
  src/main/scala/system/ExampleBoomSystem.scala
Labels: enhancement

#239 Feb. Rocket Bump
  .circleci/build-riscv-tools.sh
  .circleci/build-run-csmith-tests.sh
  .circleci/config.yml
  .circleci/create-hash.sh
  .circleci/do-rtl-build.sh
  .circleci/prepare-for-rtl-build.sh
  ROCKETCHIP_VERSION
  src/main/scala/common/tile.scala
  src/main/scala/exu/core.scala
  src/main/scala/exu/fp-pipeline.scala
  src/main/scala/exu/register-read/regfile.scala
  src/main/scala/system/BoomSubsystem.scala
  src/main/scala/system/Generator.scala
Labels: cleanup, enhancement

#238 [bpu] change bpu to adhere to style guide | misc cleanup + comments
  src/main/scala/bpu/bpd-pipeline.scala
  src/main/scala/bpu/bpd/br-predictor.scala
  src/main/scala/bpu/bpd/gshare/gshare.scala
  src/main/scala/bpu/bpd/simple-predictors/base-only.scala
  src/main/scala/bpu/bpd/simple-predictors/simple-predictors.scala
  src/main/scala/bpu/bpd/tage/tage-table.scala
  src/main/scala/bpu/bpd/tage/tage.scala
  src/main/scala/bpu/btb/bim.scala
  src/main/scala/bpu/btb/btb-sa.scala
  src/main/scala/bpu/btb/btb.scala
  src/main/scala/bpu/btb/dense-btb.scala
  src/main/scala/bpu/misc/2bc-table.scala
  src/main/scala/common/configs.scala
  src/main/scala/common/parameters.scala
  src/main/scala/exu/execution-units/functional-unit.scala
  src/main/scala/ifu/branch-checker.scala
  src/main/scala/ifu/fetch-control-unit.scala
  src/main/scala/ifu/fetch-target-queue.scala
  src/main/scala/ifu/frontend.scala
Labels: cleanup

#247 use the pointer bootrom in the main project folder
  src/main/scala/common/configs.scala
Labels: cleanup, enhancement

#250 toBools -> asBools
  src/main/scala/bpu/btb/bim.scala
  src/main/scala/bpu/btb/dense-btb.scala
  src/main/scala/bpu/misc/2bc-table.scala
  src/main/scala/exu/core.scala
  src/main/scala/exu/register-read/regfile-custom.scala
  src/main/scala/ifu/fetch-control-unit.scala
  src/main/scala/util/seqmem-transformable.scala
Labels: cleanup

#254 Change BoomConfig to use GShare by default
  src/main/scala/common/configs.scala
Labels: enhancement, performance bug
