Repository riscv-boom/riscv-boom, pull requests merged in 2019-08, with the labels that each got.

#355 [general] Migrate BOOM Integration to Chipyard
  .circleci/build-riscv-tools.sh
  .circleci/build-run-csmith-tests.sh
  .circleci/defaults.sh
  .circleci/do-rtl-build.sh
  .circleci/prepare-for-rtl-build.sh
  .github/ISSUE_TEMPLATE.md
  CHIPYARD.hash
  README.md
  docs/sections/boom-ecosystem.rst
  docs/sections/debugging.rst
  docs/sections/faq.rst
  docs/sections/intro-overview/boom-repository.rst
  docs/sections/intro-overview/index.rst
  docs/sections/intro-overview/quick-start.rst
  docs/sections/verification.rst
  src/main/scala/common/config-mixins.scala
  src/main/scala/common/configs.scala
  src/main/scala/system/BoomTestSuites.scala
  src/main/scala/system/ConfigMixins.scala
  src/main/scala/system/Configs.scala
  src/main/scala/system/Generator.scala
  src/main/scala/system/TestHarness.scala
Labels: docs, enhancement

#365 Remove the ECC Config
  src/main/scala/common/configs.scala
Labels: cleanup

#354 [core] Support breakpoints
  src/main/scala/common/micro-op.scala
  src/main/scala/common/parameters.scala
  src/main/scala/exu/core.scala
  src/main/scala/exu/decode.scala
  src/main/scala/exu/execution-units/execution-unit.scala
  src/main/scala/exu/execution-units/functional-unit.scala
  src/main/scala/ifu/fetch-buffer.scala
  src/main/scala/ifu/fetch-control-unit.scala
  src/main/scala/ifu/frontend.scala
  src/main/scala/system/BoomTestSuites.scala
Labels: missing feature

#368 update bullet points in docs
  docs/sections/intro-overview/boom-repository.rst
Labels: bug, docs

#361 [ren] Delayed Allocation
  src/main/scala/exu/core.scala
  src/main/scala/exu/rename/rename-busytable.scala
  src/main/scala/exu/rename/rename-freelist.scala
  src/main/scala/exu/rename/rename-maptable.scala
  src/main/scala/exu/rename/rename-stage.scala
Labels: cleanup, enhancement

#369 Dcache3 dual
  src/main/scala/common/parameters.scala
  src/main/scala/exu/core.scala
  src/main/scala/exu/execution-units/execution-units.scala
  src/main/scala/exu/fp-pipeline.scala
  src/main/scala/exu/rob.scala
  src/main/scala/lsu/dcache.scala
  src/main/scala/lsu/lsu.scala
  src/main/scala/lsu/mshrs.scala
  src/main/scala/lsu/tlb.scala
Labels: DO NOT MERGE

#375 Make BIM have cleaner name
  src/main/scala/bpu/btb/bim.scala
Labels: cleanup

#376 [ren] Fix RT_PAS passthrough
  src/main/scala/exu/core.scala
  src/main/scala/exu/rename/rename-stage.scala
Labels: bug
