Repository riscv-boom/riscv-boom, pull requests merged in 2020-05, with the labels that each got.

#461 RC bump to add new coreParam set to default
  src/main/scala/common/parameters.scala
Labels: enhancement

#409 FireSim CI
  .circleci/README.md
  .circleci/build-run-csmith-tests.sh
  .circleci/build-toolchains.sh
  .circleci/clean-old-files.sh
  .circleci/config.yml
  .circleci/create-hash.sh
  .circleci/defaults.sh
  .circleci/do-rtl-build.sh
  .circleci/firesim-afi-failed.sh
  .circleci/firesim-build-afi.sh
  .circleci/firesim-build-workload.sh
  .circleci/firesim-configs/firesim-boom-singlecore-no-nic-l2-llc4mb-ddr3/buildroot/config_runtime.ini
  .circleci/firesim-configs/firesim-boom-singlecore-no-nic-l2-llc4mb-ddr3/buildroot/firemarshal_config
  .circleci/firesim-configs/firesim-boom-singlecore-no-nic-l2-llc4mb-ddr3/config_build.ini
  .circleci/firesim-configs/firesim-boom-singlecore-no-nic-l2-llc4mb-ddr3/config_build_recipes.ini
  .circleci/firesim-configs/firesim-boom-singlecore-no-nic-l2-llc4mb-ddr3/coremark/config_runtime.ini
  .circleci/firesim-configs/firesim-boom-singlecore-no-nic-l2-llc4mb-ddr3/coremark/firemarshal_config
  .circleci/firesim-configs/firesim-boom-singlecore-no-nic-l2-llc4mb-ddr3/fedora/config_runtime.ini
  .circleci/firesim-configs/firesim-boom-singlecore-no-nic-l2-llc4mb-ddr3/fedora/firemarshal_config
  .circleci/firesim-configs/firesim-boom-singlecore-no-nic-l2-llc4mb-ddr3/spec17-intspeed-test-600/config_runtime.ini
  .circleci/firesim-configs/firesim-boom-singlecore-no-nic-l2-llc4mb-ddr3/spec17-intspeed-test-600/firemarshal_config
  .circleci/firesim-init-manager.sh
  .circleci/firesim-instance-resize-root.json
  .circleci/firesim-run-finished.sh
  .circleci/firesim-run-workload.sh
  .circleci/prepare-for-rtl-build.sh
  .circleci/run-tests.sh
  CHIPYARD.hash
Labels: ci, enhancement

#464 [ci] Small speedup to FireSim CI
  .circleci/firesim-init-manager.sh
Labels: ci, enhancement

#466 [ci] Misc CI Fixes
  .circleci/build-toolchains.sh
  .circleci/clean-old-files.sh
  .circleci/config.yml
  .circleci/defaults.sh
  .circleci/do-rtl-build.sh
  .circleci/install-verilator.sh
  .circleci/prepare-for-rtl-build.sh
Labels: ci
